// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWntNAibT1xHQR0kjCmBHVuAq70A2Lnxw',
    appId: '1:815523649259:web:cce2057e4b5f176e38d0ae',
    messagingSenderId: '815523649259',
    projectId: 'tasklist-6dae3',
    authDomain: 'tasklist-6dae3.firebaseapp.com',
    storageBucket: 'tasklist-6dae3.firebasestorage.app',
    measurementId: 'G-5E12E2V483',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu-s_mCyqCg07tVBU2gb_5dPmowQ-QRVM',
    appId: '1:815523649259:android:64e3c2b767327fbd38d0ae',
    messagingSenderId: '815523649259',
    projectId: 'tasklist-6dae3',
    storageBucket: 'tasklist-6dae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHAGR181nMZ-XgrAXdQE2gH0Ov893VSB8',
    appId: '1:815523649259:ios:5d83dbd22c23bffc38d0ae',
    messagingSenderId: '815523649259',
    projectId: 'tasklist-6dae3',
    storageBucket: 'tasklist-6dae3.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHAGR181nMZ-XgrAXdQE2gH0Ov893VSB8',
    appId: '1:815523649259:ios:5d83dbd22c23bffc38d0ae',
    messagingSenderId: '815523649259',
    projectId: 'tasklist-6dae3',
    storageBucket: 'tasklist-6dae3.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWntNAibT1xHQR0kjCmBHVuAq70A2Lnxw',
    appId: '1:815523649259:web:ccc18f61a529298838d0ae',
    messagingSenderId: '815523649259',
    projectId: 'tasklist-6dae3',
    authDomain: 'tasklist-6dae3.firebaseapp.com',
    storageBucket: 'tasklist-6dae3.firebasestorage.app',
    measurementId: 'G-SM15E6PF14',
  );
}
